<a href="https://colab.research.google.com/github/rameshindojin-rgb/harsh/blob/main/Pandas_1904.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pandas: Framework - clean data

#1) missing data
#2) duplicate data
#3) wrong data type
#4) wrong data


'''
id | name | age (int) (required)
1 |  abc| '16'
2 | ajay | male
3 | abhay |
1 | krish | 16
4 | sanjay| 18
'''

NameError: name 'name' is not defined

In [ ]:
#Difference between array and list

#array : homogenous (same type of data)
#list : hetergenous (it can have any type of data)

x= [1,2,'a', True]

x= [1,2,3,4,5]

In [ ]:
#series: its like a column in a table. its only for one dimensional array

import pandas as pd

a= [1,7,2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [ ]:
myvar[1]

np.int64(7)

In [ ]:
myvar = pd.Series(a, index = ["x","y","z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
myvar['y']

np.int64(7)

In [ ]:
#dataframe: 2 dimensional (rows and columns)

import pandas as pd

data = {
  "calories": [420,10,100,50],
  "duration": [50,5,50,65]
}

df = pd.DataFrame(data )

print(df)

   calories  duration
0       420        50
1        10         5
2       100        50
3        50        65

In [ ]:
#loc vs iloc
#loc: access row and column by label, used when you want to acces rows and columns by their label names
#iloc: access data based on their integer position.

#df.loc[0, 'calories'] #i can use the name of the columns(labels) to get the data back
df.iloc[0,1] # we can only use the indexes of both row and column

np.int64(420)

In [ ]:
import pandas as pd
df=pd.read_csv('/content/customers.csv')
df

   customerid name  age
0           1    a   16
1           2    b   20
2           3    c   21
3           4    d   18
4           5    e   19

In [ ]:
df.iloc[0,0]

np.int64(1)

In [ ]:
#df[iloc] : access rows and columns by integer(index) positions

df.iloc[2,1]

np.int64(103)

In [ ]:
#loc: we can mention the name of the row or column to extract data
#iloc: we can only mention the integer values of rows and columns

In [ ]:
#reading the data into dataframes
import pandas as pd
df = pd.read_csv('/content/data_test.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
#head : to get the top sample of data to make sure we got the right data or to understand the schema.
df.head() #top 5 rows
df.tail() #bottom 5 rows

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
#df.info() : it gives you information about your df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  5 non-null      int64
 1   name        5 non-null      object
 2   age         5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
#json (java script object notation): most common way for systems to exchange data between themselves.
import pandas as pd
#/content/sample_data/anscombe.json
df = pd.read_json('/content/sample_data/anscombe.json')

In [ ]:
df.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [ ]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
01/01/1900
#remove duplicates
#delete null values or fill null values
#fix data types
#wrong data

In [ ]:
import pandas as pd
df = pd.read_csv('/content/data.csv')

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
#fillna - fill null values with something.
#something - fixed value
#something - provided by business
#something  - mean(average) | median (middle value) | mode (most occuring value)
#dropna - delete the null values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:

newdf = df.dropna()
newdf.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  29 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     29 non-null     int64
 3   Maxpulse  29 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  164 non-null    int64
 1   Pulse     164 non-null    int64
 2   Maxpulse  164 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB

In [ ]:
df.dropna(inplace= True)

In [ ]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [ ]:
import pandas as pd
df = pd.read_csv('/content/data.csv')

In [ ]:
df.fillna(130, inplace = True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           130    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26-12-2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('/content/data (1).csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/data (1).csv'

In [ ]:
df['Calories'].fillna(130, inplace = True)

/tmp/ipython-input-4206768765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(130, inplace = True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26-12-2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
#mean , median , mode

df = pd.read_csv('/content/data.csv')
x=df['Calories'].mean()
x

np.float64(304.68)

In [ ]:
df
df['Calories'].fillna(x, inplace=True)
df

/tmp/ipython-input-1489018199.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(x, inplace=True)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26-12-2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [ ]:
df = pd.read_csv('/content/data (1).csv')

In [ ]:
df['Calories'].fillna(x, inplace=True)

<ipython-input-24-7f9c351309aa>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60  '2020/12/25'    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [ ]:
df = pd.read_csv('/content/data (1).csv')

In [ ]:
x = df['Calories'].mode()
x

0    300.0
Name: Calories, dtype: float64

In [ ]:
df['Calories'].fillna(x, inplace=True)

<ipython-input-12-7f9c351309aa>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     291.2
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26/12/2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     291.2
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df = pd.read_csv('/content/data (1).csv')

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26/12/2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
x = df['Calories'].mean()

In [ ]:
df.fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45        304.68    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26/12/2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [ ]:
df = pd.read_csv('/content/data (1).csv')

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    26/12/2020    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df['Calories'].fillna(x, inplace=True)

<ipython-input-38-7f9c351309aa>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(x, inplace=True)

In [ ]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60    26/12/2020    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [ ]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('/content/data (1).csv')

df['Date'].fillna("'1900/01/01'", inplace=True)

<ipython-input-40-3975600539>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna("'1900/01/01'", inplace=True)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
x= df['Calories'].mean()
df.fillna(x,inplace = True)

In [ ]:
df['Date']= pd.to_datetime(df['Date']).dt.strftime('%d-%m-%Y')

In [ ]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
4         45 2020-12-05    117       148    406.00
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7        450 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
9         60 2020-12-10     98       124    269.00
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
17        60 2020-12-17    100       120    300.00
18        45 2020-12-18     90       112    304.68
19        60 2020-12-19    103       123    323.00
20        45 2020-12-20     97       125    243.00
21        60 2020-12-21    108       131    364.20
22        45 1900-01-01    100       119    282.00
23        60 2020-12-23    130       101    300.00
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-25    100       120    250.00
27        60 2020-12-27     92       118    241.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30
31        60 2020-12-31     92       115    243.00

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 1.5 KB

In [ ]:
#validations: checks before tranformations and after transformation

#row count validation: actual vs expected number of rows .
#schema validation: expecctd number of columns vs actual columns
#data type validation: expeccted datatypes vs actual datatypes
#missing data validation: count of missing data.
#wrong data validation: expected data vs actual data
#duplicate data validation.

In [ ]:
for i in df.index:
  if df.loc[i,'Duration'] > 60:
    df.loc[i,'Duration'] = 60

In [ ]:
df

    Duration       Date  Pulse  Maxpulse    Calories
0         60 2020-12-01    110       130  409.100000
1         60 2020-12-02    117       145  479.000000
2         60 2020-12-03    103       135  340.000000
3         45 2020-12-04    109       175  282.400000
4         45 2020-12-05    117       148  406.000000
5         60 2020-12-06    102       127  300.000000
6         60 2020-12-07    110       136  374.000000
7        120 2020-12-08    104       134  253.300000
8         30 2020-12-09    109       133  195.100000
9         60 2020-12-10     98       124  269.000000
10        60 2020-12-11    103       147  329.300000
11        60 2020-12-12    100       120  250.700000
13        60 2020-12-13    106       128  345.300000
14        60 2020-12-14    104       132  379.300000
15        60 2020-12-15     98       123  275.000000
16        60 2020-12-16     98       120  215.200000
17        60 2020-12-17    100       120  300.000000
18        45 2020-12-18     90       112  305.462069
19        60 2020-12-19    103       123  323.000000
20        45 2020-12-20     97       125  243.000000
21        60 2020-12-21    108       131  364.200000
23        60 2020-12-23    130       101  300.000000
24        45 2020-12-24    105       132  246.000000
25        60 2020-12-25    102       126  334.500000
26        60 2020-12-25    100       120  250.000000
27        60 2020-12-27     92       118  241.000000
28        60 2020-12-28    103       132  305.462069
29        60 2020-12-29    100       132  280.000000
30        60 2020-12-30    102       129  380.300000
31        60 2020-12-31     92       115  243.000000

In [ ]:
# I have a csv file coming into a folder evey morning 12 am cst(central standard time). the csv file is sent by the finance team ,
#we need to read the csv file into a df and then we need to tranform the data which includes the below issues.
#1) we need to remove duplicates
#2) fill null values with  mean if its a numerical value, if its date value fill it with 01011900, if its a string value fill it with 'unknown'
#2) create new aggregrated columns which inlcudes the below columns:

#Total revenue
#total expenses
#profit
#gross margin
#operating income
#accounts receivables
#accounts payables,
#year over year growth

1000000 * 30 columns > 130mb

#Once the data is cleaned move the data in parquet format and save the data in another folder.

#file format: csv, json, parquet, avro, orc, excel

#parquet: is a file format, it is mainly used for big data processing. it uses columnar storage, the data already compressed in the file which mean it consumes less space and
#finally the data is stored in binary format which means humans cannot read it.



#avro: rowbased
#supports compression
#compression  techique : snappy
#used for heave write operations, schema evolution.
#realtime streaming.

#ORC: columnar
#compression techniques.
#best for read heavy : analytics

#parquet: columnar
#compressed data
#read heavy: analytical , complex queries



import pandas as pd

df= pd.read_parquet('/content/finance_data (3).parquet')
df

,Unnamed: 0,Date,Revenue,Expenses,COGS,Operating_Expenses,Depreciation,Amortization,Cash_Inflows,Cash_Outflows,AR,AP,Department
0,0,2025-03-07 00:00:00,3497.0,1789.0,810.0,272.0,62,173,2713,1184,1292,484,Sales
1,1,2025-03-07 01:00:00,4374.0,677.0,659.0,727.0,165,181,2125,669,174,1115,Marketing
2,2,2025-03-07 02:00:00,2091.0,1561.0,1376.0,361.0,114,182,1444,553,1482,828,Finance
3,3,2025-03-07 03:00:00,4244.0,1981.0,681.0,489.0,185,128,2287,1810,290,553,HR
4,4,2025-03-07 04:00:00,1312.0,1076.0,335.0,539.0,184,139,2861,1701,1487,980,Legal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,2025-03-07 00:00:00,4606.0,1659.0,815.0,368.0,153,72,2683,1692,832,662,Sales
101,101,2025-03-07 01:00:00,NaN,NaN,NaN,NaN,164,89,2142,774,898,480,Marketing
102,102,2025-03-07 02:00:00,4107.0,1459.0,997.0,411.0,174,129,2284,953,1497,632,Finance
103,103,2025-03-07 03:00:00,1620.0,1470.0,1169.0,905.0,107,125,2954,2367,397,192,HR
104,104,2025-03-07 04:00:00,2302.0,1622.0,1180.0,406.0,106,104,2306,1105,1028,163,Legal

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
df.to_parquet('/content/california_housing_train.parquet')
df= pd.read_parquet('/content/california_housing_train.parquet')
df.to_csv('/content/california_housing_train.csv')

In [ ]:
df = pd.read_parquet('/content/california_housing_train.parquet')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# Generating 100 sample records for a finance dashboard with random values
# Simulate the imperfect data as you requested
# Create initial finance data with duplicates, null values, and wrong date formats
#kaggle website for sample data


#VVIP info*********************this code is only to prepare sample data so please ignore the code its not part of your syllabus.************************


import pandas as pd
import numpy as np

#ignore the below it is used to create sample data , for you you ll be extractiug data from csv files.

imperfect_data = {
    'Date': pd.date_range('2025-03-07 00:00:00', periods=100, freq='H').append(pd.date_range('2025-03-07 00:00:00', periods=5, freq='H')),
    'Revenue': np.random.randint(1000, 5000, size=105),
    'Expenses': np.random.randint(500, 2000, size=105),
    'COGS': np.random.randint(300, 1500, size=105),
    'Operating_Expenses': np.random.randint(200, 1000, size=105),
    'Depreciation': np.random.randint(50, 200, size=105),
    'Amortization': np.random.randint(50, 200, size=105),
    'Cash_Inflows': np.random.randint(1000, 3000, size=105),
    'Cash_Outflows': np.random.randint(500, 2500, size=105),
    'AR': np.random.randint(100, 1500, size=105),
    'AP': np.random.randint(100, 1500, size=105),
}

#import data from csv
#Assume we are reading data from a path into a df
#df = pd.read_csv('/content/finance.csv')


# Convert to DataFrame
df_imperfect = pd.DataFrame(imperfect_data)

# Add some null values
null_rows = np.random.choice(df_imperfect.index, size=15, replace=False)
df_imperfect.loc[null_rows, 'Revenue'] = np.nan
df_imperfect.loc[null_rows, 'Expenses'] = np.nan
df_imperfect.loc[null_rows, 'Operating_Expenses'] = np.nan
df_imperfect.loc[null_rows, 'COGS'] = np.nan

# Add some string column and introduce "unknown" value
df_imperfect['Department'] = ['Sales', 'Marketing', 'Finance', 'HR', 'Legal'] * 21
df_imperfect.loc[10:20, 'Department'] = np.nan  # Some nulls for Department

# Introduce wrong date formats by manually changing some Date values
wrong_dates = df_imperfect.loc[20:30, 'Date']
wrong_dates = wrong_dates.apply(lambda x: x.replace(hour=15) if x.hour == 0 else x)  # Change some hours
df_imperfect.loc[20:30, 'Date'] = wrong_dates

df_imperfect.to_csv('/content/data.csv')


#print(df_imperfect.to_csv())

/tmp/ipython-input-1528311973.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'Date': pd.date_range('2025-03-07 00:00:00', periods=100, freq='H').append(pd.date_range('2025-03-07 00:00:00', periods=5, freq='H')),

In [ ]:

#extraction

# I have a csv file coming into a folder evey morning 12 am cst(central standard time). the csv file is sent by the finance team ,
#we need to read the csv file into a df and then we need to tranform the data which includes the below issues.


#tranformation
#1) we need to remove duplicates
#2) fill null values with  mean if its a numerical value, if its date value fill it with 01012025, if its a string value fill it with unknown
#2) create new aggregrated columns which inlcudes the below columns:
#Total revenue
#total expenses
#profit
#gross margin
#operating income
#accounts receivables
#accounts payables.
#year ove year growth


#loading
#Once the data is cleaned move the data in parquet format and save the data in another folder.

#Medallion Architecture

#Bronze Layer: Raw data


#Silver layer: tranformations (drop duplicates, fixing null values, changing datatypes, removing null values)


#Gold Layer: Aggregate columns are built for reporting. (this is where the reporting happens from)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-9-c9fea8599a30>, line 1)

In [ ]:
#this is my starting point for the project
#load the csv file
import pandas as pd
#path= "D:\Users\krish\Downloads\financedata.csv"
df = pd.read_csv('/content/data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          105 non-null    int64
 1   Date                105 non-null    object
 2   Revenue             90 non-null     float64
 3   Expenses            90 non-null     float64
 4   COGS                90 non-null     float64
 5   Operating_Expenses  90 non-null     float64
 6   Depreciation        105 non-null    int64
 7   Amortization        105 non-null    int64
 8   Cash_Inflows        105 non-null    int64
 9   Cash_Outflows       105 non-null    int64
 10  AR                  105 non-null    int64
 11  AP                  105 non-null    int64
 12  Department          94 non-null     object
dtypes: float64(4), int64(7), object(2)
memory usage: 10.8+ KB

In [ ]:
#drop Duplicates
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          105 non-null    int64
 1   Date                105 non-null    object
 2   Revenue             90 non-null     float64
 3   Expenses            90 non-null     float64
 4   COGS                90 non-null     float64
 5   Operating_Expenses  90 non-null     float64
 6   Depreciation        105 non-null    int64
 7   Amortization        105 non-null    int64
 8   Cash_Inflows        105 non-null    int64
 9   Cash_Outflows       105 non-null    int64
 10  AR                  105 non-null    int64
 11  AP                  105 non-null    int64
 12  Department          94 non-null     object
dtypes: float64(4), int64(7), object(2)
memory usage: 10.8+ KB

In [ ]:
#numerical columns fill it with mean

df['Revenue'].fillna(df['Revenue'].mean(), inplace=True)
df['Expenses'].fillna(df['Expenses'].mean(), inplace=True)
df['COGS'].fillna(df['COGS'].mean(), inplace=True)
df['Operating_Expenses'].fillna(df['Operating_Expenses'].mean(), inplace=True)
df['Depreciation'].fillna(df['Depreciation'].mean(), inplace=True)
df['Amortization'].fillna(df['Amortization'].mean(), inplace=True)

/tmp/ipython-input-4235462585.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Revenue'].fillna(df['Revenue'].mean(), inplace=True)
/tmp/ipython-input-4235462585.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Expenses'].fillna(df['Expenses'].mean(), inplace=True)
/tmp/ipython-input-4235462585.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['COGS'].fillna(df['COGS'].mean(), inplace=True)
/tmp/ipython-input-4235462585.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Operating_Expenses'].fillna(df['Operating_Expenses'].mean(), inplace=True)
/tmp/ipython-input-4235462585.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Depreciation'].fillna(df['Depreciation'].mean(), inplace=True)
/tmp/ipython-input-4235462585.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amortization'].fillna(df['Amortization'].mean(), inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          105 non-null    int64
 1   Date                105 non-null    object
 2   Revenue             105 non-null    float64
 3   Expenses            105 non-null    float64
 4   COGS                105 non-null    float64
 5   Operating_Expenses  105 non-null    float64
 6   Depreciation        105 non-null    int64
 7   Amortization        105 non-null    int64
 8   Cash_Inflows        105 non-null    int64
 9   Cash_Outflows       105 non-null    int64
 10  AR                  105 non-null    int64
 11  AP                  105 non-null    int64
 12  Department          94 non-null     object
dtypes: float64(4), int64(7), object(2)
memory usage: 10.8+ KB

In [ ]:
df['Date'].fillna('01011900', inplace=True)

/tmp/ipython-input-747715580.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna('01011900', inplace=True)

In [ ]:
df

,Unnamed: 0,Date,Revenue,Expenses,COGS,Operating_Expenses,Depreciation,Amortization,Cash_Inflows,Cash_Outflows,AR,AP,Department
0,0,2025-03-07 00:00:00,4561.000000,924.0,1085.000000,722.000000,145,173,1588,1984,1200,205,Sales
1,1,2025-03-07 01:00:00,2039.000000,510.0,834.000000,921.000000,134,68,1727,1529,1453,117,Marketing
2,2,2025-03-07 02:00:00,2544.000000,580.0,1233.000000,855.000000,131,130,1445,1780,681,495,Finance
3,3,2025-03-07 03:00:00,1019.000000,1479.0,994.000000,412.000000,50,78,2803,1386,715,799,HR
4,4,2025-03-07 04:00:00,2810.133333,1261.0,869.955556,567.655556,106,121,2636,648,338,144,Legal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,2025-03-07 00:00:00,1699.000000,1631.0,946.000000,492.000000,108,156,2630,2404,1194,829,Sales
101,101,2025-03-07 01:00:00,2810.133333,1261.0,869.955556,567.655556,143,174,1980,1465,1433,636,Marketing
102,102,2025-03-07 02:00:00,4842.000000,633.0,374.000000,348.000000,122,194,2479,1026,737,1424,Finance
103,103,2025-03-07 03:00:00,3568.000000,1815.0,608.000000,232.000000,159,161,2070,1493,592,399,HR
104,104,2025-03-07 04:00:00,4365.000000,1343.0,920.000000,342.000000,59,85,2830,1659,1284,1246,Legal

In [ ]:
df['Department'].fillna('unknown', inplace=True)

/tmp/ipython-input-1168827375.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna('unknown', inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          105 non-null    int64
 1   Date                105 non-null    object
 2   Revenue             105 non-null    float64
 3   Expenses            105 non-null    float64
 4   COGS                105 non-null    float64
 5   Operating_Expenses  105 non-null    float64
 6   Depreciation        105 non-null    int64
 7   Amortization        105 non-null    int64
 8   Cash_Inflows        105 non-null    int64
 9   Cash_Outflows       105 non-null    int64
 10  AR                  105 non-null    int64
 11  AP                  105 non-null    int64
 12  Department          105 non-null    object
dtypes: float64(4), int64(7), object(2)
memory usage: 10.8+ KB

In [ ]:
#aggregrated columns
#total revenue: revenue
#total expense: expense
#profit: revenue - expense
#gross margin: (revenue - COGS)/ revenue
#operating income : revenue-operating expense
#EBITDA (earnings befre interest, tax, depreciation and amortization): operatingincome+depreciation + amortization
#accounts receivables: AR
#accounts payables. AP
#year ove year growth : 5% . yoy = revenue * 0.05


df['total_revenue'] = df['Revenue']
df['total_expense'] = df['Expenses']
df['profit'] = df['Revenue'] - df['Expenses']
df['gross_margin'] = (df['Revenue'] - df['COGS'])/df['Revenue']
df['operating_income'] = df['Revenue'] - df['Operating_Expenses']
df['EBITDA'] = df['operating_income'] + df['Depreciation'] + df['Amortization']
df['accounts_receivables'] = df['AR']
df['accounts_payables'] = df['AP']
df['year_over_year_growth'] = df['Revenue'] * 0.05

In [ ]:
df.head()

,Unnamed: 0,Date,Revenue,Expenses,COGS,Operating_Expenses,Depreciation,Amortization,Cash_Inflows,Cash_Outflows,...,Department,total_revenue,total_expense,profit,gross_margin,operating_income,EBITDA,accounts_receivables,accounts_payables,year_over_year_growth
0,0,2025-03-07 00:00:00,4561.000000,924.0,1085.000000,722.000000,145,173,1588,1984,...,Sales,4561.000000,924.0,3637.000000,0.762114,3839.000000,4157.000000,1200,205,228.050000
1,1,2025-03-07 01:00:00,2039.000000,510.0,834.000000,921.000000,134,68,1727,1529,...,Marketing,2039.000000,510.0,1529.000000,0.590976,1118.000000,1320.000000,1453,117,101.950000
2,2,2025-03-07 02:00:00,2544.000000,580.0,1233.000000,855.000000,131,130,1445,1780,...,Finance,2544.000000,580.0,1964.000000,0.515330,1689.000000,1950.000000,681,495,127.200000
3,3,2025-03-07 03:00:00,1019.000000,1479.0,994.000000,412.000000,50,78,2803,1386,...,HR,1019.000000,1479.0,-460.000000,0.024534,607.000000,735.000000,715,799,50.950000
4,4,2025-03-07 04:00:00,2810.133333,1261.0,869.955556,567.655556,106,121,2636,648,...,Legal,2810.133333,1261.0,1549.133333,0.690422,2242.477778,2469.477778,338,144,140.506667

In [ ]:
#save it in parquet format

#parkay : prounce
#it is columnar storage
#it is compressed
#it is binary format
#it is read heavy

#it is used for large scale data mainly for machine learning and AI

#csv: comma seperate value > it just like excel.

df.to_parquet('/content/finance_data.parquet')

df =pd.read_parquet('/content/finance_data.parquet')

In [ ]:
df

,Unnamed: 0,Date,Revenue,Expenses,COGS,Operating_Expenses,Depreciation,Amortization,Cash_Inflows,Cash_Outflows,...,Department,total_revenue,total_expense,profit,gross_margin,operating_income,EBITDA,accounts_receivables,accounts_payables,year_over_year_growth
0,0,2025-03-07 00:00:00,1169.0,744.0,1464.0,240.0,93,79,2790,1213,...,Sales,1169.0,744.0,425.0,-0.252352,929.0,1101.0,1394,717,58.45
1,1,2025-03-07 01:00:00,3071.0,1586.0,935.0,943.0,170,116,1379,1092,...,Marketing,3071.0,1586.0,1485.0,0.695539,2128.0,2414.0,1223,299,153.55
2,2,2025-03-07 02:00:00,1211.0,967.0,1178.0,372.0,98,71,2129,1414,...,Finance,1211.0,967.0,244.0,0.027250,839.0,1008.0,570,1396,60.55
3,3,2025-03-07 03:00:00,3762.0,1878.0,899.0,861.0,184,63,2105,1750,...,HR,3762.0,1878.0,1884.0,0.761031,2901.0,3148.0,1148,1037,188.10
4,4,2025-03-07 04:00:00,3896.0,1659.0,1175.0,592.0,131,156,1507,1247,...,Legal,3896.0,1659.0,2237.0,0.698409,3304.0,3591.0,335,1375,194.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,100,2025-03-07 00:00:00,1900.0,1869.0,763.0,220.0,62,72,1686,2211,...,Sales,1900.0,1869.0,31.0,0.598421,1680.0,1814.0,349,494,95.00
101,101,2025-03-07 01:00:00,3104.0,1325.0,463.0,832.0,107,168,2947,1651,...,Marketing,3104.0,1325.0,1779.0,0.850838,2272.0,2547.0,619,425,155.20
102,102,2025-03-07 02:00:00,1443.0,1499.0,796.0,322.0,183,160,1468,1201,...,Finance,1443.0,1499.0,-56.0,0.448371,1121.0,1464.0,181,1184,72.15
103,103,2025-03-07 03:00:00,3953.0,1597.0,845.0,314.0,54,163,1469,1628,...,HR,3953.0,1597.0,2356.0,0.786238,3639.0,3856.0,329,509,197.65
104,104,2025-03-07 04:00:00,2774.0,1925.0,1053.0,377.0,128,116,1946,1440,...,Legal,2774.0,1925.0,849.0,0.620404,2397.0,2641.0,872,1376,138.70

In [ ]:
#pandas: merge

import pandas as pd
df1 = pd.DataFrame({'id':[1,2,5,4],'class':[9,10,11,12]})
df2 = pd.DataFrame({'id':[1,2,3,4],'student':['a','b','c','d']})
df1

# student table:
# studentid pk | name | age
# 1 | a | 16
# 2 | b| 18
# 3| c | 19


# marks table:

# marksid pk|studentid fk | subject | marks
# 1|1 | math | 90
# 2|2 | science | 92
# 3|4| english | 88






inner join: matching elements between the 2 tables
1 |a|16|math|90
2|b|18|science|92

left join : all elements from the left table and matching elements from the right table and where there is no match it will have null values
1 |a|16|math|90
2|b|18|science|92
3|c|19|null |null

right join : all elements from the right table and matching elements from the left table and where there is no match it will have null values
1 |a|16|math|90
2|b|18|science|92
4|null|null|english|88

full outer join: all elements from both tables and where there is no match it will have null values
1 |a|16|math|90
2|b|18|science|92
3|c|19|null |null
4|null|null|english|88

# table1   |   table2
# id1      |    id2
# 1             1
# 1             2
# 2             4
# 3             null
# 4             2
# null          3
# null          4
# 2             null
# 5             7

# 1  1
# 1  1
# 2  2
# 2  2
# 2  2
# 2  2
# 3  3
# 4  4
# 4  4


# null null
# null null
# 5  null
# 1  1
# 1  1
# 2  2
# 2  2
# 2  2
# 2  2
# 3  3
# 4  4
# 4  4
# null null
# null null
# null 7



# inner join: 1,1,2,2,2,2,3,4,4

# left join:  1,1,2,2,2,2,3,4,4,null, null, 5

# right join:1,1,2,2,2,2,3,4,4, null, null, 7

# full outer join: 1,1,2,2,2,2,3,4,4 , null, null, 5, null, null, 7

   id  class
0   1      9
1   2     10
2   5     11
3   4     12

In [ ]:
df2

   id student
0   1       a
1   2       b
2   3       c
3   4       d

In [ ]:
result = pd.merge(df1,df2, on='id', how = 'inner')

In [ ]:
result

   id  class student
0   1    9.0       a
1   2   10.0       b
2   3    NaN       c
3   4   12.0       d

In [ ]:
#joins : inner join, left join, right join , full outer join.

#self, cartesian(cross)

In [ ]:
#inner join : it gives only matching data from both the tables

import pandas as pd

df1 = pd.DataFrame({'id':[1,2,3,4],'Name':['krish','ajay', 'adveer','anuj']})

df2 = pd.DataFrame({'id':[3,4,5],'age':[25,28,22]})

output = pd.merge(df1,df2, on='id',how= 'inner')




# 1 KRISH NULL
# 2 AJAY NULL
# 3 ADVEER 25
# 4 ANUJ 28
output


output = pd.merge(df1,df2, on='id',how= 'right')

3 ADVEER 25
4 ANUJ 28
5 NULL 22

print(output)

#left join : all elemnts from left table and any matching elements from right table

output = pd.merge(df1,df2, on='id' , how ='left')

id | name | age
1   krish  null
2   ajay   null
3   adveer 25
4   anuj   28

#right join: all elements from right table and any matching elements from the left table.

id | name | age

3   adveer 25
4   anuj   28
5   null   22

output = pd.merge(df1,df2, on='id' , how ='outer')


id | name | age

1   krish  null
2   ajay   null
3   adveer 25
4   anuj   28
5   null   22




#full outer join: all elements from both tables

   id    Name   age
0   1   krish   NaN
1   2    ajay   NaN
2   3  adveer  25.0
3   4    anuj  28.0
4   5     NaN  22.0

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
    'city':['bangalore','ajmer','kolkata','delhi'],
    'id': [1,2,3,4],
    'Name':['krish','ajay','adveer','anuj']
})

df2 = pd.DataFrame({
    'city':['kolkata','ajmer','bangalore','delhi'],
    'id': [3,4,1,2],
    'age': [25,28,22,24]
})

In [ ]:
output = pd.merge(df1,df2, on=['id'], how='inner')

In [ ]:
output

      city_x  id    Name     city_y  age
0  bangalore   1   krish  bangalore   22
1      ajmer   2    ajay      delhi   24
2    kolkata   3  adveer    kolkata   25
3      delhi   4    anuj      ajmer   28

In [ ]:
df1 = pd.DataFrame({
    'id': [1,2,3],
    'Name':['john','Anna','Peter']
})

df2 = pd.DataFrame({
    'id': [3,4,5],
    'age': [25,28,22]
})

df3 = pd.DataFrame({
    'id': [1,2,3],
    'country':['USA','UK','India']
})

In [ ]:
output  = pd.merge(df1,df2, on='id',how = 'inner')

In [ ]:
newdf = pd.merge(output,df3, on='id', how='inner')

In [ ]:
newdf

   id   Name  age country
0   3  Peter   25   India

In [ ]:
#pivot:
import pandas as pd
df = pd.DataFrame({
    'date':['2021-01-01', '2021-01-01','2021-01-02','2021-01-02'],
    'city':['newyork', 'los angeles', 'newyork','los angeles'],
    'temperature':[32,75,34,77]})

In [ ]:
df

         date         city  temperature
0  2021-01-01      newyork           32
1  2021-01-01  los angeles           75
2  2021-01-02      newyork           34
3  2021-01-02  los angeles           77

In [ ]:
newdf = df.pivot(index='date', columns='city', values='temperature')

In [ ]:
newdf

city        los angeles  newyork
date
2021-01-01           75       32
2021-01-02           77       34

In [ ]:
#pivot examples


import pandas as pd

data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [32, 75, 34, 77],
    'Humidity': [80, 60, 70, 65],
    'Wind Speed': [10, 15, 12, 14]
}

df = pd.DataFrame(data)
print(df)

         Date         City  Temperature  Humidity  Wind Speed
0  2023-01-01     New York           32        80          10
1  2023-01-01  Los Angeles           75        60          15
2  2023-01-02     New York           34        70          12
3  2023-01-02  Los Angeles           77        65          14

In [ ]:

newdf = df.pivot(index = 'Date', columns = 'City', values = ['Temperature','Humidity','Wind Speed'])
print(newdf)

           Temperature             Humidity           Wind Speed
City       Los Angeles New York Los Angeles New York Los Angeles New York
Date
2023-01-01          75       32          60       80          15       10
2023-01-02          77       34          65       70          14       12

In [ ]:

'''
date      losangeles newyork
2023-01-01 75     32
2023-01-02 77     34
'''

In [ ]:
#normalize

import pandas as pd
import json

data1 = {
    'id':123,
    'name':'krish',
    'address':{
        'street':'123 main st',
        'city':'bangalore',
        'state':'karnataka'
    }
}

df = pd.json_normalize(data1)
print(df)

    id   name address.street address.city address.state
0  123  krish    123 main st    bangalore     karnataka

In [ ]:
df

    id   name address.street address.city address.state
0  123  krish    123 main st    bangalore     karnataka

In [ ]:
data2 = [
    {
    'id':'456',
    'name':'ajay',
    'phone':'1234567890',
    'postcode':'560001',
    'orders':[
        {'order_id': 'A1','item':'laptop','price':1000},
        {'order_id': 'A2','item':'mobile','price':500}
    ]},
    {
    'id':'789',
    'name':'krish',
    'phone':'1234567890',
    'postcode':'560001',
    'orders':[
        {'order_id': 'B1','item':'laptop','price':1000},
        {'order_id': 'B2','item':'mobile','price':500}
    ]}

]

In [ ]:
df= pd.json_normalize(data2,record_path='orders', meta=['id','name'])

In [ ]:
df

  order_id    item  price   id   name
0       A1  laptop   1000  456   ajay
1       A2  mobile    500  456   ajay
2       B1  laptop   1000  789  krish
3       B2  mobile    500  789  krish

In [ ]:
#file formats

#csv (comma seperated value)(structured) | excel (xlsx,xlsb,xlsm) (structured) | word (unstructured) |
#pdf (unstructured) | json (semi structured) | parquet(columnar storage) | avro(row based)  | orc(columnar based)


#worked file formats:
#csv | json | parquet | excel


#database: email ingestion
#file format will be in csv or json.

#download and move the file into a centralised foleder (SFTP folder)

#jdbc connection: url | username | password| port number | database name | table name : csv | json

#api connections: (application programming interface): request library : url| autentication details | query string (filter)

In [ ]:
#parquet : file format which is very commonly used in big data environment.
#Column storage: It is faster to search data in columnar storage.
#Faster queries: very fast to determine location of data.
#mainly in big data, we have lot Read and write operations. optimised in parquet format
#data is compressed, it consuming less space.
#parallelism : support parallel processing

#schema evolution: add one or more columns or remove columns it handles the evolved schema automatically.
#Includes metadata , (data about data) (column names, types, schema information)
# mostly used for  ETL | big data processing.
#binary format, so humans cannot read it.

In [ ]:
import pandas as pd

df = pd.DataFrame ({
    'name':['alice','bob','charlie'],
    'age':[25,30,35],
    'city':['newyork','sanfrancisco','losangeles']
})

df.to_parquet('/content/data.parquet')

In [ ]:
newdf = pd.read_parquet('/content/data.parquet')

In [ ]:
newdf

      name  age          city
0    alice   25       newyork
1      bob   30  sanfrancisco
2  charlie   35    losangeles

In [ ]:
df = pd.read_csv(/content/financedata.csv)

In [ ]:
#large file : 1000000/100000 = 10
import pandas as pd

chunk = 100000


first_chunk = True

for i in pd.read_csv('path',chunksize = chunk):
  i['uppercity'] = i['city'].str.upper()
  i.to_csv('path', mode=  'a', index = False, header = first_chunk)
  first_chunk = False

In [ ]:
for i in range(10):
  print(i)

  name  age  marks
0  jay   23   90.3

In [ ]:
#merge 10 files into a single file using pandas

import pandas as pd
import glob

#glob is used to list all files in a specific folder.

files = glob.glob('/content/csv/*.csv')
files
#use pd.concat which will merge all dataframes into one. I used a list comprehension which will read csvfiles in the fileslist and pd.concat will merge them one by one.
#ignore_index = True : reset the index based on the newdataframe

mergedf = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

#to_csv: write the new mergeddf to a new csv file

mergedf.to_csv('/content/csv/newcsv.csv', index= False)

['/content/csv/3.csv',
 '/content/csv/1.csv',
 '/content/csv/newcsv.csv',
 '/content/csv/2.csv']

In [ ]:
df = pd.read_csv('/content/csv/newcsv.csv')
df

,id,name,age,uppercasename,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1.0,a,16.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,b,15.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,c,21.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,a,22.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,b,25.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6.0,c,27.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7.0,a,30.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,b,32.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,c,35.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1.0,a,16.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2.0,b,15.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3.0,c,21.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,4.0,a,22.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,5.0,b,25.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,6.0,c,27.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,7.0,a,30.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,8.0,b,32.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,9.0,c,35.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,1.0,a,16.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2.0,b,15.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,3.0,c,21.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,4.0,a,22.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,5.0,b,25.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,6.0,c,27.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,7.0,a,30.0,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,8.0,b,32.0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,9.0,c,35.0,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#for different columns in the files.


import pandas as pd
import glob

#glob is used to list all files in a specific folder.

files = glob.glob('/content/csv/*.csv')

dfs = []

for file in files:
  df =pd.read_csv(file)
  dfs.append(df)

mergedf = pd.concat(dfs, ignore_index=True, sort=True)

mergedf.to_csv('path', index= False)

In [ ]:
df[df['age']>30]&(df['city'] = 'bangalore')]

In [ ]:
#json normalize
import pandas as pd
import json

In [ ]:
data = [
    {
        "id": 1,
        "name": "Alice",
        "location": {
            "city": "New York",
            "state": "NY"
        },
        "skills": ["Python", "SQL"]
    },
    {
        "id": 2,
        "name": "Bob",
        "location": {
            "city": "San Francisco",
            "state": "CA"
        },
        "skills": ["Java", "AWS"]
    }
]

In [ ]:
from pandas import json_normalize

df = json_normalize(data)

In [ ]:
df

   id   name         skills  location.city location.state
0   1  Alice  [Python, SQL]       New York             NY
1   2    Bob    [Java, AWS]  San Francisco             CA

In [ ]:
import pandas as pd

data = {'orderid':'1',
        'customer':{
            'customerid':'123',
            'name':'krish',
            'address':'bangalore'
        }}
newdf = pd.json_normalize(data)

In [ ]:
newdf

  orderid customer.customerid customer.name customer.address
0       1                 123         krish        bangalore